#!/bin/bash
set -e
COMMAND=$1
shift

case $COMMAND in

  build)
    set -x
    exec ./node_modules/.bin/webpack "$@"
    ;;

  remotedev)
    set -x
    exec node remotedev.js "$@"
    ;;

  *)
    echo "Unknown command $COMMAND"
    ;;

esac
