import React from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import {
    faBoxes,
    faEnvelope,
    faFile,
    faFileArchive,
    faFileExcel,
    faFilePdf,
    faFileWord,
    faFolder,
} from '@fortawesome/free-solid-svg-icons'

import {
    AccountTree,
    AccountTreeOutlined,
    AlternateEmail,
    ArrowDownward,
    ArrowDropDown,
    ArrowUpward,
    AttachFile,
    Cancel,
    Category,
    ChevronLeft,
    ChevronRight,
    Close,
    CloudDownload,
    CloudDownloadOutlined,
    CodeOutlined,
    DateRange,
    Delete,
    DeleteOutlined,
    DoubleArrow,
    Error,
    ErrorOutline,
    Event,
    ExpandMore,
    Folder,
    FolderOutlined,
    Fullscreen,
    FullscreenExit,
    Language,
    Launch,
    LocalOffer,
    LocalOfferOutlined,
    Lock,
    LockOpen,
    MoreHoriz,
    PinDrop,
    Print,
    Room,
    SettingsApplicationsOutlined,
    SettingsEthernet,
    Sort,
    Star,
    StarOutline,
    Subject, Toc,
    Translate,
    Visibility,
    VisibilityOffOutlined,
    ZoomIn,
    ZoomOut,
} from '@material-ui/icons'

export const reactIcons = {
    categoryCollections:        <FontAwesomeIcon icon={faBoxes} size="lg" fixedWidth />,

    categoryTags:               <LocalOffer />,
    categoryDates:              <DateRange />,
    categoryType:               <Category />,
    categoryLanguage:           <Language/>,
    categoryEmail:              <AlternateEmail/>,
    categoryLocation:           <AccountTree />,
    categorySize:               <SettingsEthernet />,
    ocr:                        <Translate/>,
    event:                      <Event />,
    tree:                       <AccountTree />,
    chevronLeft:                <ChevronLeft />,
    chevronRight:               <ChevronRight />,
    chevronDown:                <ExpandMore />,
    arrowUp:                    <ArrowUpward />,
    arrowDown:                  <ArrowDownward />,
    dropDown:                   <ArrowDropDown />,
    location:                   <Folder />,
    contentFiles:               <FolderOutlined />,
    pinned:                     <PinDrop />,
    unpinned:                   <Room />,
    doubleArrow:                <DoubleArrow />,
    cancel:                     <Cancel />,
    delete:                     <Delete />,
    deleteOutlined:             <DeleteOutlined />,
    visibility:                 <Visibility />,
    visibilityOutlined:         <VisibilityOffOutlined />,
    recommended:                <Error />,
    recommendedOutlined:        <ErrorOutline />,
    star:                       <Star />,
    starOutlined:               <StarOutline />,
    download:                   <CloudDownload />,
    downloadOutlined:           <CloudDownloadOutlined />,
    content:                    <Subject />,
    privateTag:                 <Lock />,
    publicTag:                  <LockOpen />,
    close:                      <Close />,
    sort:                       <Sort />,
    pgp:                        <Lock />,
    openNewTab:                 <Launch />,
    attachment:                 <AttachFile />,
    zoomIn:                     <ZoomIn />,
    zoomOut:                    <ZoomOut />,
    fullscreen:                 <Fullscreen />,
    fullscreenExit:             <FullscreenExit />,
    print:                      <Print />,
    contentTab:                 <Toc />,
    tagsTab:                    <LocalOfferOutlined />,
    metaTab:                    <SettingsApplicationsOutlined />,
    codeTab:                    <CodeOutlined />,
    headersTab:                 <AccountTreeOutlined />,
    moreFiles:                  <MoreHoriz />,

    typeFolder:                 <FontAwesomeIcon icon={faFolder} size="lg" fixedWidth />,
    typeArchive:                <FontAwesomeIcon icon={faFileArchive} size="lg" fixedWidth />,
    typeEmail:                  <FontAwesomeIcon icon={faEnvelope} size="lg" fixedWidth />,
    typePdf:                    <FontAwesomeIcon icon={faFilePdf} size="lg" fixedWidth />,
    typeDoc:                    <FontAwesomeIcon icon={faFileWord} size="lg" fixedWidth />,
    typeXls:                    <FontAwesomeIcon icon={faFileExcel} size="lg" fixedWidth />,
    typeEmailArchive:           <FontAwesomeIcon icon={faFileArchive} size="lg" fixedWidth />,
    typeFile:                   <FontAwesomeIcon icon={faFile} size="lg" fixedWidth />,
}
