import React from 'react'
import { SvgIcon } from '@material-ui/core'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import {
    faLayerGroup,
    faMapPin,
    faAngleDoubleRight,
    faSearch,
    faSearchPlus,
    faRedoAlt,
} from '@fortawesome/free-solid-svg-icons'

import {
    AccountTree,
    AccountTreeOutlined,
    AlternateEmail,
    ArrowDownward,
    ArrowDropDown,
    ArrowUpward,
    AttachFile,
    Cancel,
    Category,
    ChevronLeft,
    ChevronRight,
    Close,
    CloudDownload,
    CloudDownloadOutlined,
    CodeOutlined,
    DateRange,
    Delete,
    DeleteOutlined,
    Error,
    ErrorOutline,
    Event,
    ExpandMore,
    Folder,
    FolderOutlined,
    Fullscreen,
    FullscreenExit,
    Language,
    Launch,
    List,
    LocalOffer,
    LocalOfferOutlined,
    Lock,
    LockOpen,
    MoreVert,
    Print,
    SettingsApplicationsOutlined,
    SettingsEthernet,
    Sort,
    Star,
    StarOutline,
    Subject, Toc,
    Translate,
    ViewStream,
    Visibility,
    VisibilityOffOutlined,
    ZoomIn,
    ZoomOut,
} from '@material-ui/icons'

import folder, { ReactComponent as FolderIcon } from '../../icons/folder-line.svg'
import archive, { ReactComponent as ArchiveIcon } from '../../icons/file-zip-line.svg'
import email, { ReactComponent as EmailIcon } from '../../icons/mail-line.svg'
import pdf, { ReactComponent as PdfIcon } from '../../icons/file-pdf-line.svg'
import doc, { ReactComponent as DocIcon } from '../../icons/file-word-line.svg'
import xls, { ReactComponent as XlsIcon } from '../../icons/file-excel-line.svg'
import file, { ReactComponent as FileIcon } from '../../icons/file-line.svg'

const FAIcon = ({ icon, style, className }) => React.createElement(FontAwesomeIcon, {
    icon,
    className,
    size: 'lg',
    style: {
        width: '1em',
        ...style,
    }
})

export const reactIcons = {
    categoryCollections:        <FAIcon icon={faLayerGroup} style={{ width: '1.25em' }} />,

    categoryTags:               <LocalOffer />,
    categoryDates:              <DateRange />,
    categoryType:               <Category />,
    categoryLanguage:           <Language/>,
    categoryEmail:              <AlternateEmail/>,
    categoryLocation:           <AccountTree />,
    categorySize:               <SettingsEthernet />,
    ocr:                        <Translate/>,
    event:                      <Event />,
    tree:                       <AccountTree />,
    chevronLeft:                <ChevronLeft />,
    chevronRight:               <ChevronRight />,
    chevronDown:                <ExpandMore />,
    arrowUp:                    <ArrowUpward />,
    arrowDown:                  <ArrowDownward />,
    dropDown:                   <ArrowDropDown />,
    location:                   <Folder />,
    contentFiles:               <FolderOutlined />,
    pinned:                     <FAIcon icon={faMapPin} />,
    unpinned:                   <FAIcon icon={faMapPin} />,
    doubleArrow:                <FAIcon icon={faAngleDoubleRight} />,
    cancel:                     <Cancel />,
    delete:                     <Delete />,
    deleteOutlined:             <DeleteOutlined />,
    visibility:                 <Visibility />,
    visibilityOutlined:         <VisibilityOffOutlined />,
    recommended:                <Error />,
    recommendedOutlined:        <ErrorOutline />,
    star:                       <Star />,
    starOutlined:               <StarOutline />,
    download:                   <CloudDownload />,
    downloadOutlined:           <CloudDownloadOutlined />,
    content:                    <Subject />,
    privateTag:                 <Lock />,
    publicTag:                  <LockOpen />,
    close:                      <Close />,
    sort:                       <Sort />,
    pgp:                        <Lock />,
    openNewTab:                 <Launch />,
    attachment:                 <AttachFile />,
    zoomIn:                     <ZoomIn />,
    zoomOut:                    <ZoomOut />,
    fullscreen:                 <Fullscreen />,
    fullscreenExit:             <FullscreenExit />,
    print:                      <Print />,
    contentTab:                 <Toc />,
    tagsTab:                    <LocalOfferOutlined />,
    metaTab:                    <SettingsApplicationsOutlined />,
    codeTab:                    <CodeOutlined />,
    headersTab:                 <AccountTreeOutlined />,
    search:                     <FAIcon icon={faSearch} />,
    batchSearch:                <FAIcon icon={faSearchPlus} />,
    refresh:                    <FAIcon icon={faRedoAlt} />,
    tableView:                  <List />,
    listView:                   <ViewStream />,
    more:                       <MoreVert />,

    typeFolder:                 <SvgIcon component={ FolderIcon } />,
    typeArchive:                <SvgIcon component={ ArchiveIcon } />,
    typeEmail:                  <SvgIcon component={ EmailIcon } />,
    typePdf:                    <SvgIcon component={ PdfIcon } />,
    typeDoc:                    <SvgIcon component={ DocIcon } />,
    typeXls:                    <SvgIcon component={ XlsIcon } />,
    typeEmailArchive:           <SvgIcon component={ ArchiveIcon } />,
    typeFile:                   <SvgIcon component={ FileIcon } />,
}

export const imageIcons = {
    typeFolder:                 folder,
    typeArchive:                archive,
    typeEmail:                  email,
    typePdf:                    pdf,
    typeDoc:                    doc,
    typeXls:                    xls,
    typeEmailArchive:           archive,
    typeFile:                   file,
}
