import React from 'react'
import {
    AccountTree,
    AccountTreeOutlined,
    AlternateEmail,
    ArrowDownward,
    ArrowDropDown,
    ArrowUpward,
    AttachFile,
    Cancel,
    Category,
    ChevronLeft,
    ChevronRight,
    Close,
    CloudDownload,
    CloudDownloadOutlined,
    CodeOutlined,
    Collections,
    DateRange,
    Delete,
    DeleteOutlined,
    DoubleArrow,
    Error,
    ErrorOutline,
    Event,
    ExpandMore,
    Folder,
    FolderOutlined,
    Fullscreen,
    FullscreenExit,
    Language,
    Launch,
    LocalOffer,
    LocalOfferOutlined,
    Lock,
    LockOpen,
    PinDrop,
    Print,
    Room,
    SettingsApplicationsOutlined,
    SettingsEthernet,
    Sort,
    Star,
    StarOutline,
    Subject, Toc,
    Translate,
    Visibility,
    VisibilityOffOutlined,
    ZoomIn,
    ZoomOut,
} from '@material-ui/icons'

export const reactIcons = {
    tag:                        <LocalOffer />,
    calendar:                   <DateRange />,
    event:                      <Event />,
    category:                   <Category />,
    language:                   <Language/>,
    email:                      <AlternateEmail/>,
    tree:                       <AccountTree />,
    size:                       <SettingsEthernet/>,
    ocr:                        <Translate/>,
    collections:                <Collections />,
    chevronLeft:                <ChevronLeft />,
    chevronRight:               <ChevronRight />,
    chevronDown:                <ExpandMore />,
    arrowUp:                    <ArrowUpward />,
    arrowDown:                  <ArrowDownward />,
    dropDown:                   <ArrowDropDown />,
    folder:                     <Folder />,
    folderOutlined:             <FolderOutlined />,
    pinned:                     <PinDrop />,
    unpinned:                   <Room />,
    doubleArrow:                <DoubleArrow />,
    cancel:                     <Cancel />,
    delete:                     <Delete />,
    deleteOutlined:             <DeleteOutlined />,
    visibility:                 <Visibility />,
    visibilityOutlined:         <VisibilityOffOutlined />,
    recommended:                <Error />,
    recommendedOutlined:        <ErrorOutline />,
    star:                       <Star />,
    starOutlined:               <StarOutline />,
    download:                   <CloudDownload />,
    downloadOutlined:           <CloudDownloadOutlined />,
    content:                    <Subject />,
    privateTag:                 <Lock />,
    publicTag:                  <LockOpen />,
    close:                      <Close />,
    sort:                       <Sort />,
    pgp:                        <Lock />,
    openNewTab:                 <Launch />,
    attachment:                 <AttachFile />,
    zoomIn:                     <ZoomIn />,
    zoomOut:                    <ZoomOut />,
    fullscreen:                 <Fullscreen />,
    fullscreenExit:             <FullscreenExit />,
    print:                      <Print />,
    contentTab:                 <Toc />,
    tagsTab:                    <LocalOfferOutlined />,
    metaTab:                    <SettingsApplicationsOutlined />,
    codeTab:                    <CodeOutlined />,
    headersTab:                 <AccountTreeOutlined />,
}
